#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=pokec-n-poisoned
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:45:00
#SBATCH --output=pokec-n-poisoned_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Your job starts in the directory where you call sbatch
cd $HOME/matthias/FairVGNN/

# Activate the Conda environment
source activate fact_cloned

bash run_pokec-n-poisoned.sh
