#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=matthias
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:40:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Your job starts in the directory where you call sbatch
cd $HOME/matthias/FairGNN/src

# Activate the Conda environment
source activate fact_cloned

# Check if CUDA is available
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117


